//
// Generated file, do not edit! Created by nedtool 5.0 from client/messages/Application.msg.
//

#ifndef __APPLICATION_M_H
#define __APPLICATION_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
// EbitSim - Enhanced BitTorrent Simulation
// This program is under the terms of the Creative Commons
// Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)
//
// You are free:
//
//    to Share - to copy, distribute and transmit the work
//    to Remix - to adapt the work
//
// Under the following conditions:
//
//    Attribution - You must attribute the work in the manner specified by the
//    author or licensor (but not in any way that suggests that they endorse you
//    or your use of the work).
//
//    Noncommercial - You may not use this work for commercial purposes.
//
//    Share Alike - If you alter, transform, or build upon this work, you may
//    distribute the resulting work only under the same or similar license to
//    this one.
//
// With the understanding that:
//
//    Waiver - Any of the above conditions can be waived if you get permission
//    from the copyright holder.
//
//    Public Domain - Where the work or any of its elements is in the public
//    domain under applicable law, that status is in no way affected by the
//    license.
//
//    Other Rights - In no way are any of the following rights affected by the
//    license:
//        - Your fair dealing or fair use rights, or other applicable copyright
//          exceptions and limitations;
//        - The author's moral rights;
//        - Rights other persons may have either in the work itself or in how
//          the work is used, such as publicity or privacy rights.
//
//    Notice - For any reuse or distribution, you must make clear to others the
//    license terms of this work. The best way to do this is with a link to this
//    web page. <http://creativecommons.org/licenses/by-nc-sa/3.0/>
//
// Author:
//     Pedro Manoel Fabiano Alves Evangelista <pevangelista@larc.usp.br>
//     Supervised by Prof Tereza Cristina M. B. Carvalho <carvalho@larc.usp.br>
//     Graduate Student at Escola Politecnica of University of Sao Paulo, Brazil
//
// Contributors:
//     Marcelo Carneiro do Amaral <mamaral@larc.usp.br>
//     Victor Souza <victor.souza@ericsson.com>
//
// Disclaimer:
//     This work is part of a Master Thesis developed by:
//        Pedro Evangelista, graduate student at
//        Laboratory of Computer Networks and Architecture
//        Escola Politecnica
//        University of Sao Paulo
//        Brazil
//     and supported by:
//        Innovation Center
//        Ericsson Telecomunicacoes S.A., Brazil.
//
// UNLESS OTHERWISE MUTUALLY AGREED TO BY THE PARTIES IN WRITING AND TO THE
// FULLEST EXTENT PERMITTED BY APPLICABLE LAW, LICENSOR OFFERS THE WORK AS-IS
// AND MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND CONCERNING THE WORK,
// EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION,
// WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
// NONINFRINGEMENT, OR THE ABSENCE OF LATENT OR OTHER DEFECTS, ACCURACY, OR THE
// PRESENCE OF ABSENCE OF ERRORS, WHETHER OR NOT DISCOVERABLE. SOME
// JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THIS
// EXCLUSION MAY NOT APPLY TO YOU.
// }}

/**
 * Enum generated from <tt>client/messages/Application.msg:76</tt> by nedtool.
 * <pre>
 * //! Types of messages send by the application to the state machines.
 * enum AppMessageType
 * {
 * 
 *     // connection sm
 *     APP_CLOSE = 100;
 *     APP_TCP_LOCAL_CLOSE = 101;
 *     APP_TCP_REMOTE_CLOSE = 102;
 *     APP_TCP_ACTIVE_CONNECTION = 103;
 *     APP_TCP_PASSIVE_CONNECTION = 104;
 *     APP_TIMEOUT_TIMER = 105;
 *     APP_KEEP_ALIVE_TIMER = 106;
 * 
 *     // download sm
 *     APP_DOWNLOAD_RATE_TIMER = 201;
 *     APP_PEER_INTERESTING = 202;
 *     APP_PEER_NOT_INTERESTING = 203;
 *     APP_SNUBBED_TIMER = 204;
 *     // upload sm
 *     APP_CHOKE_PEER = 301;
 *     APP_UNCHOKE_PEER = 302;
 *     APP_UPLOAD_RATE_TIMER = 303;
 *     APP_SEND_PIECE_MSG = 304;
 * }
 * </pre>
 */
enum AppMessageType {
    APP_CLOSE = 100,
    APP_TCP_LOCAL_CLOSE = 101,
    APP_TCP_REMOTE_CLOSE = 102,
    APP_TCP_ACTIVE_CONNECTION = 103,
    APP_TCP_PASSIVE_CONNECTION = 104,
    APP_TIMEOUT_TIMER = 105,
    APP_KEEP_ALIVE_TIMER = 106,
    APP_DOWNLOAD_RATE_TIMER = 201,
    APP_PEER_INTERESTING = 202,
    APP_PEER_NOT_INTERESTING = 203,
    APP_SNUBBED_TIMER = 204,
    APP_CHOKE_PEER = 301,
    APP_UNCHOKE_PEER = 302,
    APP_UPLOAD_RATE_TIMER = 303,
    APP_SEND_PIECE_MSG = 304
};

/**
 * Class generated from <tt>client/messages/Application.msg:101</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message ApplicationMsg
 * {
 *     int messageId @enum(AppMessageType);
 * }
 * </pre>
 */
class ApplicationMsg : public ::omnetpp::cMessage
{
  protected:
    int messageId;

  private:
    void copy(const ApplicationMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ApplicationMsg&);

  public:
    ApplicationMsg(const char *name=nullptr, int kind=0);
    ApplicationMsg(const ApplicationMsg& other);
    virtual ~ApplicationMsg();
    ApplicationMsg& operator=(const ApplicationMsg& other);
    virtual ApplicationMsg *dup() const {return new ApplicationMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getMessageId() const;
    virtual void setMessageId(int messageId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ApplicationMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ApplicationMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __APPLICATION_M_H

