//
// Generated file, do not edit! Created by nedtool 5.0 from client/messages/UserCommand.msg.
//

#ifndef __USERCOMMAND_M_H
#define __USERCOMMAND_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
// EbitSim - Enhanced BitTorrent Simulation
// This program is under the terms of the Creative Commons
// Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)
//
// You are free:
//
//    to Share - to copy, distribute and transmit the work
//    to Remix - to adapt the work
//
// Under the following conditions:
//
//    Attribution - You must attribute the work in the manner specified by the
//    author or licensor (but not in any way that suggests that they endorse you
//    or your use of the work).
//
//    Noncommercial - You may not use this work for commercial purposes.
//
//    Share Alike - If you alter, transform, or build upon this work, you may
//    distribute the resulting work only under the same or similar license to
//    this one.
//
// With the understanding that:
//
//    Waiver - Any of the above conditions can be waived if you get permission
//    from the copyright holder.
//
//    Public Domain - Where the work or any of its elements is in the public
//    domain under applicable law, that status is in no way affected by the
//    license.
//
//    Other Rights - In no way are any of the following rights affected by the
//    license:
//        - Your fair dealing or fair use rights, or other applicable copyright
//          exceptions and limitations;
//        - The author's moral rights;
//        - Rights other persons may have either in the work itself or in how
//          the work is used, such as publicity or privacy rights.
//
//    Notice - For any reuse or distribution, you must make clear to others the
//    license terms of this work. The best way to do this is with a link to this
//    web page. <http://creativecommons.org/licenses/by-nc-sa/3.0/>
//
// Author:
//     Pedro Manoel Fabiano Alves Evangelista <pevangelista@larc.usp.br>
//     Supervised by Prof Tereza Cristina M. B. Carvalho <carvalho@larc.usp.br>
//     Graduate Student at Escola Politecnica of University of Sao Paulo, Brazil
//
// Contributors:
//     Marcelo Carneiro do Amaral <mamaral@larc.usp.br>
//     Victor Souza <victor.souza@ericsson.com>
//
// Disclaimer:
//     This work is part of a Master Thesis developed by:
//        Pedro Evangelista, graduate student at
//        Laboratory of Computer Networks and Architecture
//        Escola Politecnica
//        University of Sao Paulo
//        Brazil
//     and supported by:
//        Innovation Center
//        Ericsson Telecomunicacoes S.A., Brazil.
//
// UNLESS OTHERWISE MUTUALLY AGREED TO BY THE PARTIES IN WRITING AND TO THE
// FULLEST EXTENT PERMITTED BY APPLICABLE LAW, LICENSOR OFFERS THE WORK AS-IS
// AND MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND CONCERNING THE WORK,
// EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION,
// WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
// NONINFRINGEMENT, OR THE ABSENCE OF LATENT OR OTHER DEFECTS, ACCURACY, OR THE
// PRESENCE OF ABSENCE OF ERRORS, WHETHER OR NOT DISCOVERABLE. SOME
// JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THIS
// EXCLUSION MAY NOT APPLY TO YOU.

#include "TrackerApp.h"
using inet::IPv4Address;
//#include <IPvXAddress.h>
// }}

/**
 * Enum generated from <tt>client/messages/UserCommand.msg:81</tt> by nedtool.
 * <pre>
 * enum UserCommandKind
 * {
 * 
 *     USER_COMMAND_ENTER_SWARM = 0;
 *     USER_COMMAND_LEAVE_SWARM = 1;
 * }
 * </pre>
 */
enum UserCommandKind {
    USER_COMMAND_ENTER_SWARM = 0,
    USER_COMMAND_LEAVE_SWARM = 1
};

/**
 * Class generated from <tt>client/messages/UserCommand.msg:86</tt> by nedtool.
 * <pre>
 * class UserCommand
 * {
 * }
 * </pre>
 */
class UserCommand : public ::omnetpp::cObject
{
  protected:

  private:
    void copy(const UserCommand& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UserCommand&);

  public:
    UserCommand();
    UserCommand(const UserCommand& other);
    virtual ~UserCommand();
    UserCommand& operator=(const UserCommand& other);
    virtual UserCommand *dup() const {return new UserCommand(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UserCommand& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UserCommand& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>client/messages/UserCommand.msg:89</tt> by nedtool.
 * <pre>
 * class EnterSwarmCommand extends UserCommand
 * {
 *     TorrentMetadata torrentMetadata;
 *     bool seeder;
 *     IPvXAddress trackerAddress;
 *     int trackerPort;
 * }
 * </pre>
 */
class EnterSwarmCommand : public ::UserCommand
{
  protected:
    TorrentMetadata torrentMetadata;
    bool seeder;
//    IPvXAddress trackerAddress;
    int trackerPort;

  private:
    void copy(const EnterSwarmCommand& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EnterSwarmCommand&);

  public:
    EnterSwarmCommand();
    EnterSwarmCommand(const EnterSwarmCommand& other);
    virtual ~EnterSwarmCommand();
    EnterSwarmCommand& operator=(const EnterSwarmCommand& other);
    virtual EnterSwarmCommand *dup() const {return new EnterSwarmCommand(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual TorrentMetadata& getTorrentMetadata();
    virtual const TorrentMetadata& getTorrentMetadata() const {return const_cast<EnterSwarmCommand*>(this)->getTorrentMetadata();}
    virtual void setTorrentMetadata(const TorrentMetadata& torrentMetadata);
    virtual bool getSeeder() const;
    virtual void setSeeder(bool seeder);
//    virtual IPvXAddress& getTrackerAddress();
//    virtual const IPvXAddress& getTrackerAddress() const {return const_cast<EnterSwarmCommand*>(this)->getTrackerAddress();}
//    virtual void setTrackerAddress(const IPvXAddress& trackerAddress);
    virtual int getTrackerPort() const;
    virtual void setTrackerPort(int trackerPort);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EnterSwarmCommand& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EnterSwarmCommand& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>client/messages/UserCommand.msg:96</tt> by nedtool.
 * <pre>
 * class LeaveSwarmCommand extends UserCommand
 * {
 *     int infoHash;
 * }
 * </pre>
 */
class LeaveSwarmCommand : public ::UserCommand
{
  protected:
    int infoHash;

  private:
    void copy(const LeaveSwarmCommand& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LeaveSwarmCommand&);

  public:
    LeaveSwarmCommand();
    LeaveSwarmCommand(const LeaveSwarmCommand& other);
    virtual ~LeaveSwarmCommand();
    LeaveSwarmCommand& operator=(const LeaveSwarmCommand& other);
    virtual LeaveSwarmCommand *dup() const {return new LeaveSwarmCommand(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getInfoHash() const;
    virtual void setInfoHash(int infoHash);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LeaveSwarmCommand& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LeaveSwarmCommand& obj) {obj.parsimUnpack(b);}


#endif // ifndef __USERCOMMAND_M_H

